# Assignment 50 - Factoring a Rotation over an angle $\theta$ about an arbitrary axis $\hat{\mathbf{n}}$

**Claim**: Any rotation about an arbitrary axis $\hat{\mathbf{n}}$ by an angle $\theta$ can be generated by a conjugate rotation over $\theta$ about the $z$ axis. 

The sense of ''conjugacy'' here comes from the theory of groups. If $a, b \ \in \ <G, \ \cdot>$, then $a$ and $b$ are to be conjugate to each other provided that there exists $g \in \ <G, \ \cdot>$ such that $b = gag^{-1}$. 

In [1]:
from sympy import *
from sympy import sin, cos
from sympy.abc import a, b, c
from sympy.vector import CoordSys3D

theta = symbols('theta')

# passive rotation matrices
Rx = Matrix([[1.0, 0.0, 0.0],[0.0, cos(theta), sin(theta)],[0.0, -sin(theta), cos(theta)]])
Ry = Matrix([[cos(theta), 0.0, -sin(theta)], [0.0, 1.0, 0.0], [sin(theta), 0, cos(theta)]])
Rz = Matrix([[cos(theta), sin(theta), 0.0], [-sin(theta), cos(theta), 0.0], [0.0, 0.0, 1.0]])

# active rotation matrices
RX = Matrix([[1.0, 0.0, 0.0],[0.0, cos(theta), -sin(theta)],[0.0, sin(theta), cos(theta)]])
RY = Matrix([[cos(theta), 0.0, sin(theta)], [0.0, 1.0, 0.0], [-sin(theta), 0, cos(theta)]])
RZ = Matrix([[cos(theta), -sin(theta), 0.0], [sin(theta), cos(theta), 0.0], [0.0, 0.0, 1.0]])

In [2]:
Rx

Matrix([
[1.0,         0.0,        0.0],
[0.0,  cos(theta), sin(theta)],
[0.0, -sin(theta), cos(theta)]])

In [3]:
RX

Matrix([
[1.0,        0.0,         0.0],
[0.0, cos(theta), -sin(theta)],
[0.0, sin(theta),  cos(theta)]])

In [4]:
trigsimp(Rx*RX)

Matrix([
[1.0, 0, 0],
[  0, 1, 0],
[  0, 0, 1]])

In [5]:
Ry

Matrix([
[cos(theta), 0.0, -sin(theta)],
[       0.0, 1.0,         0.0],
[sin(theta),   0,  cos(theta)]])

In [6]:
RY

Matrix([
[ cos(theta), 0.0, sin(theta)],
[        0.0, 1.0,        0.0],
[-sin(theta),   0, cos(theta)]])

In [7]:
trigsimp(Ry*RY)

Matrix([
[1,   0, 0],
[0, 1.0, 0],
[0,   0, 1]])

In [8]:
Rz

Matrix([
[ cos(theta), sin(theta), 0.0],
[-sin(theta), cos(theta), 0.0],
[        0.0,        0.0, 1.0]])

In [9]:
RZ

Matrix([
[cos(theta), -sin(theta), 0.0],
[sin(theta),  cos(theta), 0.0],
[       0.0,         0.0, 1.0]])

In [10]:
trigsimp(Rz*RZ)

Matrix([
[1, 0,   0],
[0, 1,   0],
[0, 0, 1.0]])

In [11]:
n = Matrix([a, b, c])
n

Matrix([
[a],
[b],
[c]])

We can make a geometric argument that the radius, $R$, of the circle that the unit vector $\hat{n}$ sweeps out as it's rotated about the $x$ - axis into the $x - z$ plane is:

$$R = \sqrt{b^{2} + c^{2}}$$

Moreover, once the unit vector $\hat{n}$ is rotated into the $x - z$ plane, it will have components:

$$(a, 0, \sqrt{b^{2} + c^{2}}) $$

In [12]:
RX * n

Matrix([
[                      1.0*a],
[b*cos(theta) - c*sin(theta)],
[b*sin(theta) + c*cos(theta)]])

If we solve the implied system of linear equations from the bottom two rows of the above, we find that:

$$\sin(\theta) = \frac{b}{\sqrt{b^{2} + c^{2}}}$$

and 

$$\cos({\theta}) = \frac{c}{\sqrt{b^{2} + c^{2}}}$$

we can make these replacements in the roation matrix $R_{x}$:

In [13]:
RXXX = RX.subs({cos(theta): c/sqrt(b**2 + c**2), sin(theta): b/sqrt(b**2 + c**2)})

In [14]:
RXXX

Matrix([
[1.0,                 0.0,                  0.0],
[0.0, c/sqrt(b**2 + c**2), -b/sqrt(b**2 + c**2)],
[0.0, b/sqrt(b**2 + c**2),  c/sqrt(b**2 + c**2)]])

In [15]:
# now we find the form of Ry
RYY = RY * (RXXX * n)
RYY

Matrix([
[ 1.0*a*cos(theta) + (b**2/sqrt(b**2 + c**2) + c**2/sqrt(b**2 + c**2))*sin(theta)],
[                                                                               0],
[-1.0*a*sin(theta) + (b**2/sqrt(b**2 + c**2) + c**2/sqrt(b**2 + c**2))*cos(theta)]])

Observe that once we rotate around the y - axis, a vector that lies entirely in x - z plane will now lie entirely along the z - axis. This observation gives a way to solve the above for the values of $\sin(\theta)$ and $\cos(\theta)$, since the vector now has coordinates given by 

$$(0, 0, \sqrt{a^{2} + b^{2} + c^{2}}) = (0, 0, 1)$$

Solving the implied system of linear equations above for $\sin(\theta)$ and $\cos(\theta)$ yields:

$$\sin(\theta) = -a, \ \ \cos(\theta) = \sqrt{b^{2} + c^{2}}$$

In [16]:
RYYY = RY.subs({cos(theta): sqrt(b**2 + c**2), sin(theta): -a})

In [17]:
RYYY

Matrix([
[sqrt(b**2 + c**2), 0.0,                -a],
[              0.0, 1.0,               0.0],
[                a,   0, sqrt(b**2 + c**2)]])

In [18]:
(RYYY * (RXXX * n))

Matrix([
[ 1.0*a*sqrt(b**2 + c**2) - a*(b**2/sqrt(b**2 + c**2) + c**2/sqrt(b**2 + c**2))],
[                                                                             0],
[1.0*a**2 + sqrt(b**2 + c**2)*(b**2/sqrt(b**2 + c**2) + c**2/sqrt(b**2 + c**2))]])

In [19]:
Rxxx = RXXX.inv()

In [20]:
simplify(RXXX)

Matrix([
[1.0,                   0,                    0],
[  0, c/sqrt(b**2 + c**2), -b/sqrt(b**2 + c**2)],
[  0, b/sqrt(b**2 + c**2),  c/sqrt(b**2 + c**2)]])

In [21]:
simplify(Rxxx * RXXX)

Matrix([
[1.0, 0, 0],
[  0, 1, 0],
[  0, 0, 1]])

In [22]:
Ryyy = RYYY.inv()

In [23]:
simplify(RYYY)

Matrix([
[sqrt(b**2 + c**2),   0,                -a],
[                0, 1.0,                 0],
[                a,   0, sqrt(b**2 + c**2)]])

In [24]:
simplify(Ryyy * RYYY)

Matrix([
[1,   0, 0],
[0, 1.0, 0],
[0,   0, 1]])

In [25]:
import numpy as np


def random3DUnitVector(seed=None, test=False):
    unit_vector = 1.0 / np.sqrt([3.0, 3.0, 3.0])
    if not test:
        # set seed
        if seed is not None:
            np.random.seed(seed)
        # unscaled vector components
        vec = np.random.uniform(0.0, 1.0, 3)
        norm = np.sqrt(np.sum((vec*vec)))
        unit_vector = vec / norm
    return unit_vector


# checkpoint 1
print("\n(Norm of vector should equal 1.0) - Norm of vector equals: ", np.sqrt(np.sum(random3DUnitVector(42)**2)))


def numericMatrix(matrix, rotation_vector):
    u, v, w = rotation_vector
    return np.array(matrix.subs({a:u, b:v, c:w}))


# checkpoint 2 
# lower left entry should equal
# the square root of 1 / 3 which is ~ 0.57735027
is_equal = numericMatrix(Ryyy, random3DUnitVector(test=True))[-1, 0] == 1.0/np.sqrt(3)
print("\nLower left entry = 1/3? : {}".format(is_equal))


def randomAngle(seed=None, n=1):
    return np.random.uniform(0, 2*np.pi,n)


randomAngle(5)

N = random3DUnitVector(seed=42)
print("\nRotation vector: {}".format(N))

def factorRotation(m1=Rxxx, m2=Ryyy, M1=RXXX, M2=RYYY, seed=None, test=False):
    N = random3DUnitVector(seed, test)
    sympy_matrices = [M1, M2, m1, m2]
    np_matrices = [np.array(numericMatrix(m, v)) for (m, v) in zip(sympy_matrices, [N]*len(sympy_matrices))]

    return np_matrices
    
    
m1, m2, M1, M2 = factorRotation(seed=42)
    
# checkpoint 3
# ensure that numeric matrices are inverses
print("\nRotX^(-1) * RotX = : \n {}".format(np.matmul(M1, m1)))
print("\nRotY^(-1) * RotY = : \n {}".format(np.matmul(M2, m2)))


def setRz(matrix=Rz, seed=None):
    return np.array(matrix.subs({theta: randomAngle(seed=42)[0]}))

                             
def generateRandom3DUnitVectors(seed=None, test=False, num=50):
    return np.array([np.array(random3DUnitVector(seed=None, test=False)) for n in range(num)])

vectors = generateRandom3DUnitVectors(seed=7, test=False, num=50)
print("\nVectors: {}".format(vectors))

def rotation(rotXInv, rotYInv, rotZ, rotY, rotX):
    T1 = np.matmul(rotY, rotX) 
    T2 = np.matmul(rotZ, T1)
    T3 = np.matmul(rotXInv, rotYInv)
    T4 = np.matmul(T3, T2)
    
    return T4


rotN = rotation(m1, m2, setRz(seed=42), M2, M1)
print("\nRotation Matrix: \n{}".format(rotN))


def rotateVectors(factored_rotation, nVectors):
    return np.matmul(factored_rotation, np.transpose(nVectors))


rotatedVectors = np.transpose(rotateVectors(rotN, vectors))


def getRotatedVectorLengths(vectors):
    return [np.dot(vectors[i], vectors[i]) for i in range(len(vectors))]


rotatedVectorLengths =  np.array(getRotatedVectorLengths(rotatedVectors))

print("\n Rotated Vector Raw Lengths: \n{}".format(rotatedVectorLengths))


(Norm of vector should equal 1.0) - Norm of vector equals:  1.0

Lower left entry = 1/3? : False

Rotation vector: [0.29797254 0.75635891 0.58235175]

RotX^(-1) * RotX = : 
 [[1.00000000000000 0 0]
 [0 1.00000000000000 0]
 [0 0 1.00000000000000]]

RotY^(-1) * RotY = : 
 [[1.00000000000000 0 0]
 [0 1.00000000000000 0]
 [0 0 1.00000000000000]]

Vectors: [[0.93830842 0.24453609 0.24449828]
 [0.05500741 0.82030212 0.56927903]
 [0.58954575 0.01713878 0.80755314]
 [0.94797403 0.24180881 0.20705973]
 [0.28942061 0.48010801 0.82808937]
 [0.53751999 0.36241067 0.76140053]
 [0.28531899 0.59754899 0.74935191]
 [0.49054795 0.84453367 0.21476871]
 [0.65437273 0.75385838 0.059109  ]
 [0.95771891 0.26881008 0.10254575]
 [0.60177478 0.61239526 0.51267842]
 [0.40329246 0.12931269 0.9058882 ]
 [0.65336769 0.18115503 0.7350466 ]
 [0.03634953 0.96117442 0.27353692]
 [0.7376993  0.34708122 0.57908062]
 [0.48452495 0.16382826 0.85929964]
 [0.51287151 0.62162539 0.59206815]
 [0.54238851 0.83628368 0.0802765

In [26]:
sum(1 - rotatedVectorLengths)/len(rotatedVectorLengths)

-1.62092561595273e-16

In [27]:
from itertools import combinations

def getDotProducts(vectrs, rotated_vectrs):
    return np.abs(np.array([np.dot(v[0], v[1]) for v in list(combinations(vectrs, 2))]) - 
                  np.array([np.dot(v[0], v[1]) for v in list(combinations(rotated_vectrs, 2))]))

In [28]:
print(max(getDotProducts(vectors, rotatedVectors)))

4.44089209850063e-16


In [29]:
np.all(getDotProducts(vectors, rotatedVectors) <= 0.000000000000001)

True

In [30]:
np.matmul(rotN, N)

array([-0.0474567847737384, -0.291523996850056, -0.955385583332462],
      dtype=object)

In [31]:
N

array([0.29797254, 0.75635891, 0.58235175])

In [32]:
np.dot(np.matmul(rotN, N), np.matmul(rotN, N))

1.00000000000000

# Analytical Part

We have equation $(13.19)$:

$$\sum_{i}v_{i}^{2} = \sum_{i, j, k}R_{ij}v_{j}R_{ik}v_{k}$$

The key statement is that $\mathbf{R}$ is a rotation $\iff \vec{v} = \mathbf{R}\vec{v^{'}} \ \ \forall \vec{v}$. 

We recognize, first of all, that both sides of the above denote inner products of a vector with itself. On the left hand side, we have the inner product of $\vec{v}$ with itself. On the right hand side, we have the inner product of the rotated vector $\vec{v^{'}} = \mathbf{R}\vec{v}$ with itself. 

To prove that the vector resulting from algorithm 6 leaves the lengths invariant, then, we need only show that the matrix giving the overall transformation is a member of $O(n)$.

But this is trivial, since the overall rotation is itself a product of orthogonal transformations. So let $R_{x}$ be the orthogonal matrix that rotates $\vec{n}$ about the $x$ axis into the $x-z$ plane, $R_{y}$ be the orthogonal matrix that rotates $\vec{n^{\prime}} = R_{x}(\vec{n})$ into the $z$ axis, and $R_{z_{\theta}}$ the orthogonal matrix that rotates $\vec{n^{\prime \prime}} = R_{y} (\vec{n^{\prime}}) \ \theta$ degrees about the $z$-axis. Then the matrix $R_{n_{\theta}}$ that gives the rotaton of $\theta$ degrees about the axis along $\vec{n}$ is: 

$$R_{n_{\theta}} = R_{x}^{-1}R_{y}^{-1}R_{z_{\theta}}R_{y}R_{x}$$

And from the above we obtain the following expression for the inverse of $R_{n_{\theta}}$:

$$R_{n_{\theta}}^{-1} = (R_{x}^{-1}R_{y}^{-1}R_{z_{\theta}}R_{y}R_{x})^{-1}$$

$$= R_{x}^{-1}R_{y}^{-1}R_{z_{\theta}}^{-1}R_{y}R_{x}$$

$$= R_{x}^{T}R_{y}^{T}R_{z_{\theta}}^{T}R_{y}R_{x}$$

$$= (R_{x}^{T}R_{y}^{T}R_{z_{\theta}}R_{y}R_{x})^{T}$$

$$= (R_{x}^{-1}R_{y}^{-1}R_{z_{\theta}}R_{y}R_{x})^{T}$$

$$= R_{n_{\theta}}^{T}$$

Since, moreover, all of the above are so-called *proper rotations* we have it that $\text{Det}(R_{n_{\theta}}) = 1$, since its determinant is just the product of all of the individual determinants and these are all equal to unity. 
So $(R_{n_{\theta}})$ is in fact an element of $SO(3)$ and is thus length preserving by the equivalence given in $(13.19)$ above. 

To demonstrate that the rotation leaves all inner-products unchanged (from which fact, when combined with the above result and the geometric definition of the inner-product, it immediately follows that the angles between vectors are preserved by the rotation), we use the result from $(13.19)$ along with the result from $(13.20)$:

$$\vec{v^{\prime}} \cdot \vec{w^{\prime}} = \mathbf{R}\vec{v} \cdot \mathbf{R}\vec{w} = \sum_{i,j,k}R_{ij}v_{j}R_{ik}w_{k} = \sum_{i,j,k}(R_{ij}R_{ik})v_{j}w_{k} = \sum_{j,k}\delta_{jk}v_{j}w_{k} = \sum_{j}v_{j}w_{j} = \vec{v} \cdot \vec{w}$$

where we have made use of the result from $(13.20)$ - $\delta_{jk} = \sum_{i}R_{ij}R_{ik}$. 